apiVersion: kubernetes.dask.org/v1
kind: DaskCluster
metadata:
  name: my-dask-cluster
  namespace: benchmarking
spec:
  worker:
    replicas: 4
    spec:
      containers:
      - name: worker
        image: "ghcr.io/dask/dask:2023.5.0-py3.10"
        imagePullPolicy: "IfNotPresent"
        args:
          - dask-worker
          - --name
          - $(DASK_WORKER_NAME)
          - --dashboard
          - --dashboard-address
          - "8788"
        ports:
          - name: http-dashboard
            containerPort: 8788
            protocol: TCP
        # Make sure to mount SSD volume!
        volumeMounts:
        - mountPath: /tmp/dask-tmpdir
          name: dask
        # Make sure to pip install!
        env:
        - name: EXTRA_PIP_PACKAGES
          value: 'aiobotocore==2.5.0 aiohttp==3.8.4 aiohttp-cors==0.7.0 aioitertools==0.11.0 aiosignal==1.3.1 appnope==0.1.3 asttokens==2.2.1 async-timeout==4.0.2 attrs==23.1.0 backcall==0.2.0 blessed==1.20.0 botocore==1.29.76 cachetools==5.3.0 certifi==2023.5.7 charset-normalizer==3.1.0 click==8.1.3 cloudpickle==2.2.1 colorful==0.5.5 dask==2023.5.0 decorator==5.1.1 distlib==0.3.6 distributed==2023.5.0 executing==1.2.0 filelock==3.12.0 frozenlist==1.3.3 fsspec==2023.5.0 google-api-core==2.11.0 google-auth==2.18.1 googleapis-common-protos==1.59.0 gpustat==1.1 grpcio==1.49.1 idna==3.4 importlib-metadata==6.6.0 ipython==8.13.2 jedi==0.18.2 Jinja2==3.1.2 jmespath==1.0.1 jsonschema==4.17.3 locket==1.0.0 MarkupSafe==2.1.2 matplotlib-inline==0.1.6 msgpack==1.0.5 multidict==6.0.4 numpy==1.24.3 nvidia-ml-py==11.525.112 opencensus==0.11.2 opencensus-context==0.1.3 packaging==23.1 pandas==2.0.1 parso==0.8.3 partd==1.4.0 pexpect==4.8.0 pickleshare==0.7.5 platformdirs==3.5.1 prometheus-client==0.16.0 prompt-toolkit==3.0.38 protobuf==4.23.1 psutil==5.9.5 ptyprocess==0.7.0 pure-eval==0.2.2 py-spy==0.3.14 pyarrow==12.0.0 pyasn1==0.5.0 pyasn1-modules==0.3.0 pydantic==1.10.7 Pygments==2.15.1 pyrsistent==0.19.3 python-dateutil==2.8.2 pytz==2023.3 PyYAML==6.0 ray==2.4.0 requests==2.31.0 rsa==4.9 s3fs==2023.5.0 six==1.16.0 smart-open==6.3.0 sortedcontainers==2.4.0 stack-data==0.6.2 tblib==1.7.0 toolz==0.12.0 tornado==6.3.2 traitlets==5.9.0 typing_extensions==4.6.0 tzdata==2023.3 urllib3==1.26.15 virtualenv==20.21.0 wcwidth==0.2.6 wrapt==1.15.0 yarl==1.9.2 zict==3.0.0 zipp==3.15.0'
        # Make sure to point Dask to tmpdir volume!
        - name: DASK_TEMPORARY_DIRECTORY
          value: /tmp/dask-tmpdir
        resources:
          limits:
            memory: 59000Mi
          requests:
            cpu: 6950m
      nodeSelector:
        eventual.internal/node-role: development
      serviceAccountName: worker
      tolerations:
      - effect: NoSchedule
        key: eventual.internal/node-role
        operator: Equal
        value: development
      - effect: NoSchedule
        key: ray.io/cluster-type
        operator: Equal
        value: dev-us-west-2c
      volumes:
      - name: dask
        emptyDir: {}
  scheduler:
    spec:
      containers:
      - name: scheduler
        image: "ghcr.io/dask/dask:2023.5.0-py3.10"
        imagePullPolicy: "IfNotPresent"
        args:
          - dask-scheduler
        ports:
          - name: tcp-comm
            containerPort: 8786
            protocol: TCP
          - name: http-dashboard
            containerPort: 8787
            protocol: TCP
        readinessProbe:
          httpGet:
            port: http-dashboard
            path: /health
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: http-dashboard
            path: /health
          initialDelaySeconds: 15
          periodSeconds: 20
        # Make sure to mount SSD volume!
        volumeMounts:
        - mountPath: /tmp/dask-tmpdir
          name: dask
        # Make sure to pip install!
        env:
        - name: EXTRA_PIP_PACKAGES
          value: 'aiobotocore==2.5.0 aiohttp==3.8.4 aiohttp-cors==0.7.0 aioitertools==0.11.0 aiosignal==1.3.1 appnope==0.1.3 asttokens==2.2.1 async-timeout==4.0.2 attrs==23.1.0 backcall==0.2.0 blessed==1.20.0 botocore==1.29.76 cachetools==5.3.0 certifi==2023.5.7 charset-normalizer==3.1.0 click==8.1.3 cloudpickle==2.2.1 colorful==0.5.5 dask==2023.5.0 decorator==5.1.1 distlib==0.3.6 distributed==2023.5.0 executing==1.2.0 filelock==3.12.0 frozenlist==1.3.3 fsspec==2023.5.0 google-api-core==2.11.0 google-auth==2.18.1 googleapis-common-protos==1.59.0 gpustat==1.1 grpcio==1.49.1 idna==3.4 importlib-metadata==6.6.0 ipython==8.13.2 jedi==0.18.2 Jinja2==3.1.2 jmespath==1.0.1 jsonschema==4.17.3 locket==1.0.0 MarkupSafe==2.1.2 matplotlib-inline==0.1.6 msgpack==1.0.5 multidict==6.0.4 numpy==1.24.3 nvidia-ml-py==11.525.112 opencensus==0.11.2 opencensus-context==0.1.3 packaging==23.1 pandas==2.0.1 parso==0.8.3 partd==1.4.0 pexpect==4.8.0 pickleshare==0.7.5 platformdirs==3.5.1 prometheus-client==0.16.0 prompt-toolkit==3.0.38 protobuf==4.23.1 psutil==5.9.5 ptyprocess==0.7.0 pure-eval==0.2.2 py-spy==0.3.14 pyarrow==12.0.0 pyasn1==0.5.0 pyasn1-modules==0.3.0 pydantic==1.10.7 Pygments==2.15.1 pyrsistent==0.19.3 python-dateutil==2.8.2 pytz==2023.3 PyYAML==6.0 ray==2.4.0 requests==2.31.0 rsa==4.9 s3fs==2023.5.0 six==1.16.0 smart-open==6.3.0 sortedcontainers==2.4.0 stack-data==0.6.2 tblib==1.7.0 toolz==0.12.0 tornado==6.3.2 traitlets==5.9.0 typing_extensions==4.6.0 tzdata==2023.3 urllib3==1.26.15 virtualenv==20.21.0 wcwidth==0.2.6 wrapt==1.15.0 yarl==1.9.2 zict==3.0.0 zipp==3.15.0'
        # Make sure to point Dask to tmpdir volume!
        - name: DASK_TEMPORARY_DIRECTORY
          value: /tmp/dask-tmpdir
        resources:
          limits:
            memory: 59000Mi
          requests:
            cpu: 6950m
      nodeSelector:
        eventual.internal/node-role: development
        failure-domain.beta.kubernetes.io/zone: us-west-2c
      serviceAccountName: worker
      tolerations:
      - effect: NoSchedule
        key: eventual.internal/node-role
        operator: Equal
        value: development
      - effect: NoSchedule
        key: ray.io/cluster-type
        operator: Equal
        value: dev-us-west-2c
      volumes:
      - name: dask
        emptyDir: {}
    service:
      type: NodePort
      selector:
        dask.org/cluster-name: my-dask-cluster
        dask.org/component: scheduler
      ports:
      - name: tcp-comm
        protocol: TCP
        port: 8786
        targetPort: "tcp-comm"
      - name: http-dashboard
        protocol: TCP
        port: 8787
        targetPort: "http-dashboard"
